### ISSUE TITLE
lattice plot 

### ISSUE THREAD

**Issue by fanglifl** [QuEraComputing/Bloqade.jl#196]
@GiggleLiu the atom sizes in the lattice plot could vary a lot, as shown in the documentation lattice page: 
https://solid-journey-b55ed955.pages.github.io/dev/lattices/

Is there any way to make sure the atoms have the same size? Or at least for the default lattice (e.g. LiebLattice(), Square()), we have the same size of atoms?

**Comment by Wang-Shengtao** [comment]
Plotting in IDE in the dark mode still shows lattices that are hard to see. I still think it's better to put a white box as a background for the lattices.
