### ISSUE TITLE
[BUG] total time mismatch in creating the SchrodingerProblem

### ISSUE THREAD

**Issue by Wang-Shengtao** [QuEraComputing/Bloqade.jl#242]
In creating the `SchrodingerProblem`, if the `total_time` is longer than the time in the Hamiltonian h, an error should be produced. If the wavefunction Ω and Δ have different total time, then `total_time` should be smaller or equal to the smaller of either one, otherwise, an error should appear.

`prob = SchrodingerProblem(reg, total_time, h);`

**Comment by Roger-luo** [comment]
I think this should be resolved in upcoming BloqadePulse.
