### ISSUE TITLE
[DOC] add benchmark link 

### ISSUE THREAD

**Issue by Wang-Shengtao** [QuEraComputing/Bloqade.jl#307]
https://github.com/Happy-Diode/Bloqade.jl/blob/9db0001f423049491a875ee29efee2ff718255a5/docs/src/emulation.md?plain=1#L108

**Comment by johnzl-777** [comment]
Whoops, spoke too soon! This should be it: https://github.com/yardstiq/bloqade_benchmarks/tree/main#results
