### ISSUE TITLE
IR generation for general waveform 

### ISSUE THREAD

**Issue by fanglifl** [QuEraComputing/Bloqade.jl#356]
Currently, only hamiltonian generated by piecewise_linear or piecewise_constant is able to be transformed to Jason. 
Could we have more general input waveform, including those specified by 'duration' and those generated by smooth function?

**Comment by weinbe58** [comment]
@Roger-luo This can probably be closed.

**Comment by weinbe58** [comment]
Completed in BloqadeSchema currently
