### ISSUE TITLE
[Feature Request] conversion from subspace register to fullspace

### ISSUE THREAD

**Issue by Roger-luo** [QuEraComputing/Bloqade.jl#364]
chatted with @maolinml and haoxiang today, and mentioned that this could be a useful thing for their calculation. Should be super easy to implement, but I'm gonna put the issue here as a backlog so I don't forget working on it when I'm back.

**Comment by hxwang-amazon** [comment]
Thank you for taking care of this! Also, this feature might also be used to fix this new bug we found, i.e., #371 .
