### ISSUE TITLE
[Feature Request] CompatHelper

### ISSUE THREAD

**Issue by Roger-luo** [QuEraComputing/Bloqade.jl#375]
need to setup CompatHelper for this repo. I need to check how subdir works for CompatHelper.

**Comment by manulpatel** [comment]
Hello @Roger-luo! I would be happy to work on this. Could you please assign me?

**Comment by ACE07-Sev** [comment]
I'd like to work on this as well. Can you kind assign me to it?

**Comment by Roger-luo** [comment]
@ACE07-Sev there is already a PR trying to fix this (but it is not working) if you also want to work on this you can submit a new PR, but I'd encourage you to take a different issue

**Comment by manulpatel** [comment]
@Roger-luo Could you please give any hints on what is failing and any leads further?

**Comment by manulpatel** [comment]
@Roger-luo Yes I have made changes and opened up a new PR. I hope this should work. It seemed prior had issues with "" quotes in subdirs.

**Comment by manulpatel** [comment]
@Roger-luo. I have opened a fresh PR, which setups CompatHelper only for main repo i.e. at top dir. For subdirs I tred to follow **[this](**url**)** but there are errors when scannnig inside `lib` dir. Your insights on this would be very helpful.

**Comment by natestemen** [comment]
@manulpatel reminder that if you get this merged by June 20th, you'll be eligible for the unitaryHACK bounty!

**Comment by manulpatel** [comment]
Thanks @natestemen for reminding! Actually I am stuck on this and not able to pass the CI tests for my changes.

**Comment by manulpatel** [comment]
@Roger-luo Could you please assign me the issue and then close it? As this would allow Unitary Hack bots to discover this issue. @natestemen The PR for this issue is successfully merged as per the deadline of 20 June AoE. Kindly consider me in the Unitary Hack 2023 for this issue.

**Comment by Roger-luo** [comment]
I just did that I'm not sure if this works or not, please let me know if it doesn't.
