### ISSUE TITLE
[BUG] Print of C6 coefficient - factor of 10

### ISSUE THREAD

**Issue by T100M** [QuEraComputing/Bloqade.jl#392]
**Describe the bug**
The value of the C6 coefficient printed in the output description is a factor of 10 larger than what is expected for the Rydberg state considered (70S) which should be 2pi*862690 MHz*(µm)^6.

Please see the screenshot below.

**Expected behavior**
The exact value should be C6 = 2*pi*862690 MHz*(µm)^6

**Screenshots**

<img width="1429" alt="Screen Shot 2022-08-16 at 6 01 28 PM" src="https://user-images.githubusercontent.com/111394921/184992953-0b17616b-f7d3-4391-8c2d-f956c3bfebf1.png">

**Version Info**
 - Julia version: 1.7.3

**Additional context**
The problem is with the printing and not with the code of the simulation.

**Comment by Roger-luo** [comment]
good catch thanks!
