### ISSUE TITLE
[Feature Request] Subspace basis indexing

### ISSUE THREAD

**Issue by jon-wurtz** [QuEraComputing/Bloqade.jl#498]
Getting basis states for a fullspace vs. subspace register has different behavior. For example, consider

```
atoms = generate_sites(ChainLattice(), 5, scale = 5)
bass = blockade_subspace(atoms,7.0)
psi_subspace = zero_state(bass)
psi_fullspace  = zero_state(5)
```
Then, if you want to look up a basis state, you can use
```
psi_fullspace[bit"10101"]
```
which works. However,
```
psi_subspace[bit"10101"]
```
does not work. I recommend that ```SubspaceArrayReg``` and ```ArrayReg``` have the same features.

**Comment by ChenZhao44** [comment]
This feature has been added in #500
