### ISSUE TITLE
remove matplotlib plotting receipts via PythonCall and use Plots directly

### ISSUE THREAD

**Issue by Roger-luo** [QuEraComputing/Bloqade.jl#595]
from 1.9+ the latency is much more reasonable, we should remove the old matplotlib calls with just the https://github.com/JuliaPy/PythonPlot.jl package

**Comment by GiggleLiu** [comment]
Can not agree more. I have run into multiple issues that caused by PythonCall.
1. repeated reinitialization of the conda environment,
2. the compilation of SciMLBasePythonCallExt runs forever due to the lock file in the .CondaPkg folder.

**Comment by GiggleLiu** [comment]
Maybe using Makie/CairoMakie is the only choice. Its using time is quite reasonable after julia 1.10.
