### ISSUE TITLE
[BUG] SciMLBase version bounded to 1 but OrdinaryDiffEq is < 6.57.0

### ISSUE THREAD

**Issue by Roger-luo** [QuEraComputing/Bloqade.jl#611]
#607 is missing a `compat` bound for `SimpleNonlinearSolve` because this package is expecting old `SciMLBase=1` to be compatible but it is not, it requires `SciMLBase=2` in latest version.

**Comment by weinbe58** [comment]
But this is not a direct dependency of the package? is there any reason why the compatibility is not handled downstream?

**Comment by Roger-luo** [comment]
because they didn't specify the upper bound of that minor version in a new patch, which makes sense as a human being but it is why it's not working

**Comment by Roger-luo** [comment]
I think this patch version is yanked FYI
