### ISSUE TITLE
[BUG] InitError: Python: ModuleNotFoundError: No module named 'matplotlib'

### ISSUE THREAD

**Issue by ryanhill1** [QuEraComputing/Bloqade.jl#616]
**Describe the bug**

`using Bloqade` $\rightarrow$ `ERROR: InitError: Python: ModuleNotFoundError: No module named 'matplotlib'`

**To Reproduce**
A code snippet to reproduce the behavior

```julia
julia> using Bloqade
ERROR: InitError: Python: ModuleNotFoundError: No module named 'matplotlib'
Python stacktrace: none
Stacktrace:
  [1] pythrow()
    @ PythonCall /opt/.julia/packages/PythonCall/wXfah/src/err.jl:94
  [2] errcheck
    @ /opt/.julia/packages/PythonCall/wXfah/src/err.jl:10 [inlined]
  [3] pyimport(m::String)
    @ PythonCall /opt/.julia/packages/PythonCall/wXfah/src/concrete/import.jl:11
  [4] __init__()
    @ Bloqade /opt/.julia/packages/Bloqade/vg0g0/src/Bloqade.jl:50
  [5] register_restored_modules(sv::Core.SimpleVector, pkg::Base.PkgId, path::String)
    @ Base ./loading.jl:1115
  [6] _include_from_serialized(pkg::Base.PkgId, path::String, ocachepath::String, depmods::Vector{Any})
    @ Base ./loading.jl:1061
  [7] _require_search_from_serialized(pkg::Base.PkgId, sourcepath::String, build_id::UInt128)
    @ Base ./loading.jl:1506
  [8] _require(pkg::Base.PkgId, env::String)
    @ Base ./loading.jl:1783
  [9] _require_prelocked(uuidkey::Base.PkgId, env::String)
    @ Base ./loading.jl:1660
 [10] macro expansion
    @ ./loading.jl:1648 [inlined]
 [11] macro expansion
    @ ./lock.jl:267 [inlined]
 [12] require(into::Module, mod::Symbol)
    @ Base ./loading.jl:1611
during initialization of module Bloqade
```

**Expected behavior**

`using Bloqade` command should go through

**Screenshots**

![Screenshot 2023-11-10 at 2 31 41 PM](https://github.com/QuEraComputing/Bloqade.jl/assets/46977852/2b23be73-9512-425a-a308-1152ea6600ea)
![Screenshot 2023-11-10 at 2 32 12 PM](https://github.com/QuEraComputing/Bloqade.jl/assets/46977852/eab63b10-7465-4c87-b34e-c025bda73852)

**Version Info**
 - Julia version: 1.9.3
 - Python version: 3.9.18
 - Matplotlib version: 3.8.1
 - PythonCall version: 0.9.15
 - Bloqade version: 0.1.25 ([#bc8e97e](https://github.com/QuEraComputing/Bloqade.jl#bc8e97e))

**Additional context**

Related issues: https://github.com/QuEraComputing/Bloqade.jl/issues/593, https://github.com/QuEraComputing/Bloqade.jl/issues/595, https://github.com/QuEraComputing/Bloqade.jl/issues/605

**Comment by mrs504aa** [comment]
I've met similar problem. I solved it by adding matplotlib through CondaPkg.
```julia
julia> using CondaPkg
(@v1.9) pkg> conda add matplotlib
```

**Comment by ryanhill1** [comment]
@mrs504aa This worked, thanks!
